### PR TITLE
Added a speed attribute to Player and changed the name of a method in Bystander, Readded Previous Files After Commit Reversion

### PR DESCRIPTION
**Pull request by marjaleenakiik**
Player has a speed attribute with associated getter and setter. Changed the name of a Bystander method to hasQuest instead of getHasQuest.

### CODE REVIEW

**Review by evagrafouille — APPROVED** [review]
Perfect for the change of the method's name in the Bystander class.

**Review by bw55555 — CHANGES_REQUESTED** [review]
Should merge in changes from main branch first and readd missing files since previous commit was reverted to fix ide issue

**Review by Yasutakahi — APPROVED** [review]
I think the change makes sense

**Review by bw55555 — APPROVED** [review]
all entities, follows clean architecture

**Review by charlietaoxl — APPROVED** [review]
Well-written comments and docstrings, overall clean

**Review by charlietaoxl — CHANGES_REQUESTED** [review]
Type is now an enum called SkillType, so instances of SKillType should now be of format "SkillType varName = SkillType.WATER" for example. Only FIRE, WATER, EARTH and AIR are constants in Type.
"private SkillType type;"
"public Player(String name, SkillType type)"

**Review by juhwansonn — DISMISSED** [review]
code and architecture look solid

**Review by mahirhassan-uoft — APPROVED** [review]
classes look good, will implement database for default values as well

**Review by charlietaoxl — APPROVED** [review]
Changes are fixed! Everything looks good, potential future additions can be discussed later.

**Review by Yasutakahi — APPROVED** [review]
I think all the change including adding armor looks very nice to me in terms of clean architecture and also the quality of the game

**Pull request merged**
