### PR TITLE
feature 6 quests connecting game

### PR DESCRIPTION
**Pull request by evagrafouille**
Made all the adequate changes to connect the different components of the Quest System (QuestInteractor, QuestGiverEvent and the rest of the game).

Remaining to be done: testing file.
I have run the game and you can know view the quests.

### CODE REVIEW

**Review by bw55555 — APPROVED** [review]
Looks good!

**Review by marjaleenakiik — DISMISSED** [review]
Allows for viewing quests. Code runs as intended.

**Review by Yasutakahi — DISMISSED** [review]
looks good!

**Review by passionfruitjello — APPROVED** [review]

**Review by bw55555 — APPROVED** [review]
reapprove, merge conflict

**Review by Yasutakahi — APPROVED** [review]
good work

**Pull request merged**
