### PR TITLE
added EnemyPotion entity and EnemyPotionHandler use case

### PR DESCRIPTION
**Pull request by Yasutakahi**
I added a new class called EnemyPotion entity and its use case called EnemyPotionHandler. This handler will be initialized and used in the EnemyTurnState. I also reimplemented the enemyAI so that it returns EnemyAction. So now Skill and EnemyPotion is returned by the respond method in the EnemyAi. The interface EnemyAction is for the future implementation (some method could be added). Database now has information about the potion (the amount of health that the potion increases), so EnemyInfo now has new instance attribute which is EnemyPotion which is initialized (depending on the value in the database). Also, I fixed some tests and added new tests for EnemyPotionHandler use case.

### CODE REVIEW

**Review by bw55555 — CHANGES_REQUESTED** [review]
it looks like EnemyAction is an interface for an entity. 
This means down the line, you will need to use instanceOf to get the right use case for the entity (since skill and enemyPotion have different method signatures)

It would be a lot easier if EnemyAction was a interface for a use case

that way the caller can just call EnemyAction.doAction with the required parameters like EnemyFacade enemy

and not worry about whether the enemyAction is a enemyPotion or enemySkill.

**Review by bw55555 — APPROVED** [review]
Great work!

**Review by mahirhassan-uoft — APPROVED** [review]
Very nice! You implemented potion to database correctly.

**Review by charlietaoxl — APPROVED** [review]
The new implementation of SkillHandler to have EnemySkillHandler is a nice implementation, will work on the PlayerSkillHandler portion but looks good otherwise.

**Pull request merged**
