### PR TITLE
final database changes + docstrings

### PR DESCRIPTION
**Pull request by mahirhassan-uoft**
- added docstrings to every method/class of database and world implementation (areas + events)
- added implementation for separate json files to more easily add data for each system

### CODE REVIEW

**Review by bw55555 — APPROVED** [review]
docstring makes sense, and splitting the database into multiple files helps a lot with organization

**Review by bw55555 — APPROVED** [review]
using string builder to fix bug with replaying message on wrong input

**Review by juhwansonn — APPROVED** [review]
looks good

**Review by Yasutakahi — APPROVED** [review]
making multiple files makes sense and it looks much cleaner now

**Pull request merged**
