### PR TITLE
implemented SaveGateway

### PR DESCRIPTION
**Pull request by passionfruitjello**
Implemented a Saving system where all Savable entities can be stored and accessed.
Also implemented SaveGateway to help load from and save to a json file.
Documentation for classes, attributes and methods all completed.
Tests to be added soon.

### CODE REVIEW

**Review by bw55555 — CHANGES_REQUESTED** [review]
Add docstrings for classes, not just methods.
Also, test the code - it looks right, but I don't know if its actually right

**Review by bw55555 — DISMISSED** [review]
looks good to me!

**Review by juhwansonn — APPROVED** [review]

**Review by bw55555 — APPROVED** [review]
refactor makes sense

**Review by juhwansonn — APPROVED** [review]

**Review by evagrafouille — APPROVED** [review]
Looks good.

**Review by bw55555 — APPROVED** [review]

**Pull request merged**
