### PR TITLE
added docstrings for StateManager

### PR DESCRIPTION
**Pull request by passionfruitjello**

### CODE REVIEW

**Review by bw55555 — APPROVED** [review]
docstring looks good

**Review by mahirhassan-uoft — APPROVED** [review]
Docstrings look good.

**Review by marjaleenakiik — APPROVED** [review]
Docstrings are thorough, describe methods accurately.

**Review by charlietaoxl — COMMENTED** [review]
Docstrings look good!

**Review by charlietaoxl — COMMENTED** [review]
Docstrings look good!

**Pull request merged**
