### PR TITLE
revert "Added a Characters package in objects, which includes the ent…

### PR DESCRIPTION
**Pull request by bw55555**
something happened bad

### CODE REVIEW

**Comment by mahirhassan-uoft** [comment]
FIX THE GAME!!

**Review by charlietaoxl — APPROVED** [review]
GET THOSE OUTTA HERE

**Review by mahirhassan-uoft — APPROVED** [review]
IM SICK OF THIS SH

**Review by marjaleenakiik — APPROVED** [review]
Gradle packages making issues, better to remove them outright.

**Pull request merged**
