### PR TITLE
Feature 10 options

### PR DESCRIPTION
**Pull request by bw55555**
Completed a way to change options
PauseMenu can be later extended to also be able to save/view inventory/other

### CODE REVIEW

**Review by marjaleenakiik — APPROVED** [review]
Code looks functional, utilizes multiple design patterns effectively (such as state). Interface methods are implemented properly. Options.java most likely does not need the textSize attribute, but it could be included in case GUI is added later so the user can change the text size. Some final changes are needed for saving functionality, but those can wait until saving is merged with main.

**Review by Yasutakahi — DISMISSED** [review]
I think the coding and pckaging are very nice and clean. Also it has test which is properly packaged so overall I think it is well coded and organized

**Review by passionfruitjello — APPROVED** [review]
Code is following clean architecture. Tests are done. Package structure is proper fixed and looks nice now.

**Review by marjaleenakiik — APPROVED** [review]
Makes sense and follows Clean Architecture. Docstrings are descriptive, code works as intended.

**Review by mahirhassan-uoft — APPROVED** [review]
refactoring fix

**Pull request merged**
