### PR TITLE
Main Menu Initial Implementation

### PR DESCRIPTION
**Pull request by marjaleenakiik**
Added some preliminary implementation of the main menu using a manager and State system in a main_menu package. Includes:

- MainMenuManager: Switches between the different States of the main menu.
- MainMenuInputValidator: Validates input for the main menu.
- MainMenuOptions: An enum for different inputs the user may use in the main menu.
- MainMenuFactory: A factory class for creating the four different States of the main menu. Used to avoid dependencies.
- MainMenuState: The main state of the main menu. Includes options for the user to switch to a new game, load a saved game, or quit the game.
- NewGameState: State of the main menu to create a new game. Awaiting saving functionality to show the user the save slots that already have a game saved. User can return to the main menu from here.
- LoadGameState: State of the main menu to load a saved game. Awaiting saving functionality to show the user information about the Player in each save slot (ex. name and description of the Player). User can return to the main menu from here.
- QuitState: State of the main menu to quit the game. User can decide whether to close the game or return to the main menu.
- Added some testing for MainMenuInputValidator in the testing files.

### CODE REVIEW

**Review by mahirhassan-uoft — DISMISSED** [review]
very well structured!

**Review by bw55555 — APPROVED** [review]
Looks good! Perhaps also write an issue to test the manager and states?

**Review by Yasutakahi — DISMISSED** [review]
Nice implementation. Good job!!!

**Review by juhwansonn — DISMISSED** [review]
looks good!

**Review by juhwansonn — APPROVED** [review]

**Review by bw55555 — APPROVED** [review]

**Review by Yasutakahi — APPROVED** [review]
Looks great!!!

**Pull request merged**
