### PR TITLE
open world gameing

### PR DESCRIPTION
**Pull request by mahirhassan-uoft**
THE GAME IS OPEN WORLD YALL TRY IT OUT IN GAME -> RUN MAIN
i didnt do events yet

### CODE REVIEW

**Review by bw55555 — APPROVED** [review]
Looks good now!

**Review by charlietaoxl — APPROVED** [review]
Read through it, it better work!

**Review by juhwansonn — APPROVED** [review]
approving now so we can start using it but I think you should add docstring for tests so we can see what exactly you are testing, also some other classes seem to be missing docstring. The code looks good and should work.

**Comment by Vinod022** [comment]
Main

**Pull request merged**
