### PR TITLE
6 feature 6 quest system

### PR DESCRIPTION
**Pull request by evagrafouille**
Created the elements required for the quest system:
* Quest object handles the creation of a quest, checking whether it is completed or not, reward distributed to the player.
* Reward (abstract class – to enable the creation of different type of tasks) & a specific type of reward adding an amount to one of the player's stats.
* Task (abstract class – to enable the creation of different type of tasks) & a specific type of tasks that required to have an exact or a minimum amount in one of the player's tasks.

Remaining: finishing the QuestManager to make the whole quest function and communicate with the rest of the game.

### CODE REVIEW

**Review by Yasutakahi — CHANGES_REQUESTED** [review]
You might want to check why the auto grading is falling, if your code depends on some other classes, try importing those classes. If its not problem with importing, you might want to look at your code and find out why the auto grading is failing

**Review by passionfruitjello — CHANGES_REQUESTED** [review]
Docstrings are good but it's unnecessary to comment and explain what you're doing for every single line of code you wrote. The code is now looking a bit messy. You might wanna remove those comments for simple code like assignment statements lol

**Review by passionfruitjello — CHANGES_REQUESTED** [review]
Also all those getter and setter functions are a bit redundant. Game structure wise, once a quest is created, you won't need to change those name and stuff. Nor will other parts of the game system need to access to those stuff. But it is recommended that you have a displayDescriptionAndTasks method to display description and tasks, it sort of function like a string representation of the quest.

**Review by passionfruitjello — CHANGES_REQUESTED** [review]
I think you might need to have something like a QuestChannel to store the list of quests. Also it is recommended to add more method to complete the feature of Quest system, for example, displayUserProgress(). Additionally you could also add different level requirements for different quests.

**Review by Yasutakahi — CHANGES_REQUESTED** [review]
For the doc string, make sure you add @param and @return so that the people who use the method can actually know what parameters should be and what it should return. Also, to make sure that the test will run correctly, create tests of the classes.

**Pull request closed without merging**
